# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pizza_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=pizza_shop.models.generate_token, max_length=40, verbose_name='Токен корзины для сессий')),
                ('archive', models.BooleanField(default=False, verbose_name='Заказ оформлен')),
                ('contact', models.CharField(default='', max_length=20, null=True, verbose_name='Контактные данные')),
            ],
            options={
                'verbose_name_plural': 'Корзины',
                'verbose_name': 'Корзина',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CartMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.Cart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name_plural': 'Блюда в корзине',
                'verbose_name': 'Блюдо в корзине',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Wrong number', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Телефон')),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='pizza_shop.Cart', verbose_name='Заказ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Контактные данные',
                'verbose_name': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, verbose_name='Тип информации')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('descr', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Ингредиенты',
                'verbose_name': 'Ингредиент',
            },
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name_plural': 'Типы ингредиентов',
                'verbose_name': 'Тип ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('title', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('weight', models.CharField(help_text='Вес блюда в граммах', max_length=70, verbose_name='Вес')),
                ('link', models.CharField(help_text='Название для использования в ссылках', max_length=80, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Latin only')], verbose_name='Ссылка')),
                ('descr', models.TextField(default='', verbose_name='Описание')),
                ('keywords', models.CharField(default='', help_text='Для поисковиков', max_length=300, verbose_name='Ключевые слова')),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Блюда',
                'verbose_name': 'Блюдо',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=pizza_shop.models.subclass_directory_path, verbose_name='Изображение')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='pizza_shop.Meal', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name_plural': 'Изображение блюд',
                'verbose_name': 'Изображение блюда',
            },
        ),
        migrations.CreateModel(
            name='MealInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Информация')),
                ('info_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.InfoType', verbose_name='Тип информации')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='pizza_shop.Meal', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name_plural': 'Информация о блюдах',
                'verbose_name': 'Информация о блюде',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('link', models.CharField(help_text='Название для использования в ссылках', max_length=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Latin only')], verbose_name='Ссылка')),
                ('img', models.ImageField(upload_to='sec_img', verbose_name='Изображение раздела')),
                ('descr', models.TextField(default='', verbose_name='Описание')),
                ('keywords', models.CharField(default='', help_text='Для поисковиков', max_length=300, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name_plural': 'Разделы',
                'verbose_name': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, verbose_name='Статус')),
                ('details', models.CharField(help_text='Более детальное описание статуса', max_length=600, verbose_name='Подробнее')),
            ],
            options={
                'verbose_name_plural': 'Статусы заказов',
                'verbose_name': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Название подраздела')),
                ('link', models.CharField(help_text='Название для использования в ссылках', max_length=70, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Latin only')], verbose_name='Ссылка')),
                ('img', models.ImageField(upload_to='subsec_img', verbose_name='Изображение подраздела')),
                ('descr', models.TextField(default='', verbose_name='Описание')),
                ('keywords', models.CharField(default='', help_text='Для поисковиков', max_length=300, verbose_name='Ключевые слова')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsecs', to='pizza_shop.Section', verbose_name='Подраздел для')),
            ],
            options={
                'verbose_name_plural': 'Подразделы',
                'verbose_name': 'Подраздел',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='subsec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='pizza_shop.SubSection', verbose_name='Подраздел'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inside',
            field=models.ManyToManyField(related_name='ingredients', to='pizza_shop.Meal', verbose_name='Содержится в'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='pizza_shop.IngredientType', verbose_name='Тип ингредиента'),
        ),
        migrations.AddField(
            model_name='cartmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.Meal', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='cart',
            name='meals',
            field=models.ManyToManyField(through='pizza_shop.CartMeal', to='pizza_shop.Meal', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='pizza_shop.State', verbose_name='Статус заказа'),
        ),
    ]
