# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pizza_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(default=pizza_shop.models.State(details='Заказ не оформлен', text='Ожидается'), on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='pizza_shop.State', verbose_name='Статус заказа'),
        ),
    ]
